/**
 * Config format validation tests — verifies that:
 * 1. Claude Code settings.json shape is correct
 * 2. Cursor .cursor/mcp.json shape is correct
 * 3. Codex CLI ~/.codex/config.json shape is correct
 * 4. Expected dist artifacts exist after build
 *
 * These tests run without any API keys or HTTP calls.
 */

import { existsSync } from "fs";
import { resolve } from "path";
import { readFile } from "fs/promises";

const REPO_ROOT = resolve(__dirname, "..");

// ---- Claude Code settings.json ----

describe("Claude Code .claude/settings.json", () => {
  let settings: {
    hooks?: Record<string, Array<{ matcher: string; hooks: Array<{ type: string; command: string }> }>>;
    env?: Record<string, string>;
  };

  beforeAll(async () => {
    const raw = await readFile(resolve(REPO_ROOT, ".claude", "settings.json"), "utf8");
    settings = JSON.parse(raw);
  });

  it("has UserPromptSubmit hook array", () => {
    expect(Array.isArray(settings.hooks?.["UserPromptSubmit"])).toBe(true);
    expect(settings.hooks!["UserPromptSubmit"].length).toBeGreaterThan(0);
  });

  it("UserPromptSubmit hook has type:command", () => {
    const hook = settings.hooks!["UserPromptSubmit"][0].hooks[0];
    expect(hook.type).toBe("command");
    expect(typeof hook.command).toBe("string");
    expect(hook.command).toMatch(/user-prompt-submit/);
  });

  it("has PostToolUse hook array", () => {
    expect(Array.isArray(settings.hooks?.["PostToolUse"])).toBe(true);
    expect(settings.hooks!["PostToolUse"].length).toBeGreaterThan(0);
  });

  it("PostToolUse hook has type:command", () => {
    const hook = settings.hooks!["PostToolUse"][0].hooks[0];
    expect(hook.type).toBe("command");
    expect(typeof hook.command).toBe("string");
    expect(hook.command).toMatch(/post-tool-use/);
  });

  it("has PreCompact hook array", () => {
    expect(Array.isArray(settings.hooks?.["PreCompact"])).toBe(true);
    expect(settings.hooks!["PreCompact"].length).toBeGreaterThan(0);
  });

  it("PreCompact hook has type:command", () => {
    const hook = settings.hooks!["PreCompact"][0].hooks[0];
    expect(hook.type).toBe("command");
    expect(typeof hook.command).toBe("string");
    expect(hook.command).toMatch(/pre-compact/);
  });
});

// ---- plugin.json (relative-path manifest for --plugin-dir CI testing) ----

describe("plugin.json (CI plugin manifest)", () => {
  let manifest: {
    name?: string;
    version?: string;
    hooks?: Record<string, unknown[]>;
    mcpServers?: Record<string, { command: string; args: string[] }>;
  };

  beforeAll(async () => {
    const raw = await readFile(resolve(REPO_ROOT, "plugin.json"), "utf8");
    manifest = JSON.parse(raw);
  });

  it("has name and version", () => {
    expect(manifest.name).toBe("dietcode");
    expect(typeof manifest.version).toBe("string");
  });

  it("has UserPromptSubmit, PostToolUse, PreCompact hooks", () => {
    expect(Array.isArray(manifest.hooks?.["UserPromptSubmit"])).toBe(true);
    expect(Array.isArray(manifest.hooks?.["PostToolUse"])).toBe(true);
    expect(Array.isArray(manifest.hooks?.["PreCompact"])).toBe(true);
  });

  it("uses relative paths (not absolute) in hook commands", () => {
    for (const hookArray of Object.values(manifest.hooks ?? {})) {
      for (const entry of hookArray as Array<{ hooks: Array<{ command: string }> }>) {
        for (const h of entry.hooks) {
          expect(h.command).not.toMatch(/^\/Users\//);
          expect(h.command).not.toMatch(/^\/home\//);
        }
      }
    }
  });

  it("has dietcode MCP server with node command", () => {
    const dietcode = manifest.mcpServers?.["dietcode"];
    expect(dietcode).toBeDefined();
    expect(dietcode!.command).toBe("node");
    expect(dietcode!.args).toContain("./dist/src/index.js");
  });
});

// ---- Cursor .cursor/mcp.json ----

describe("Cursor config format (generated by setup)", () => {
  // We validate the shape that setup.ts would generate, not a committed file.
  // The shape that setup.ts writes for Cursor:
  it("expected Cursor mcp.json shape has mcpServers.dietcode", () => {
    const cursorConfig = {
      mcpServers: {
        dietcode: {
          command: "node",
          args: ["/path/to/dist/src/index.js"],
          env: { SCALEDOWN_API_KEY: "test-key" },
        },
      },
    };
    expect(cursorConfig.mcpServers["dietcode"].command).toBe("node");
    expect(Array.isArray(cursorConfig.mcpServers["dietcode"].args)).toBe(true);
    expect(cursorConfig.mcpServers["dietcode"].env["SCALEDOWN_API_KEY"]).toBeDefined();
  });
});

// ---- Codex CLI config shape ----

describe("Codex CLI config format (generated by setup)", () => {
  it("expected Codex config.json shape has mcpServers.dietcode", () => {
    const codexConfig = {
      mcpServers: {
        dietcode: {
          command: "node",
          args: ["/path/to/dist/src/index.js"],
          env: { SCALEDOWN_API_KEY: "test-key" },
        },
      },
    };
    expect(codexConfig.mcpServers["dietcode"].command).toBe("node");
    expect(Array.isArray(codexConfig.mcpServers["dietcode"].args)).toBe(true);
  });
});

// ---- Dist artifact existence ----

describe("dist artifacts (post-build)", () => {
  const DIST = resolve(REPO_ROOT, "dist");

  const requiredArtifacts = [
    "dist/src/index.js",
    "dist/bin/setup.js",
    "dist/hooks/user-prompt-submit.js",
    "dist/hooks/post-tool-use.js",
    "dist/hooks/pre-compact.js",
    "dist/hooks/git-attribution.js",
    "dist/hooks/status.js",
  ];

  for (const artifact of requiredArtifacts) {
    it(`${artifact} exists`, () => {
      expect(existsSync(resolve(REPO_ROOT, artifact))).toBe(true);
    });
  }

  it("no source .ts files shipped in dist (.d.ts declarations are fine)", () => {
    // Verify we don't accidentally ship source files. `.d.ts` declaration
    // files are legitimate tsc output, so only flag non-declaration .ts files.
    const { execSync } = require("child_process");
    const tsFiles = execSync(
      `find ${DIST} -name "*.ts" -not -name "*.d.ts" 2>/dev/null || true`
    )
      .toString()
      .trim();
    expect(tsFiles).toBe("");
  });
});
